name: Hello World Job!

on: 
  push: 
    branches: 
      - main

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World Step
        run: echo "Hello, World!"
  print_date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date Step
        run: date
  print_directory_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Directory Step
        run: ls -la